version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Airtable
  AIRTABLE_ACCESS_TOKEN: token
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: scg-datascience
    private_key_id: 24ba415b4c583b955a36bb033a4bfcde9ad9888e
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZYdLOwCeqnwMj\nPbksY2zJ6hBjVg+S0Eqo460OZdjVfH6fkH9PQEjjTJ8oiiNKuoz/LgULCv+O6wsU\nlBaSmku1B1IKk3Fcr7InthWxEbm/DgTHhItBVa+k9RWboghONACYJ9/SB/yfUkGj\n5RDOAqLgefEYC2nzbcbU/WY3K9jXgKZk5d6TloL5g49yXsvEnVTjJndvzCtJQ0eP\nOrWDYhWNtZeLo+KKYqoqvQWB/YYF8Y6587ETUAuy7udAD/Do6HKbLUXVDNXTi4N7\n3lfR8LZpwVdE+GdPf8tWWLAZ5gadqTNaI8L+XzVu6Nvd+osPQ8e+9MTdifQ9v5kG\nndZ0RkLBAgMBAAECggEABbDCKNmqrxMUA05H14cpyFTxfjSkF8WNW4uKMQROIYor\nSswKLnHGB9Qg0djMJeUwFCCMNIRthksfP7MdzPBsr3RB0t11AXli50PDYBd2WB79\nm5Gwi+rmp7ylrFQ8MXs5lsDgoNLF3dBSr0axPf9i371ObfQFyS+mW+Jkf4FWMRUz\nUcrusbZDVig3sfTqilXsbo2qxD2PSGN+VdGOX5GXudgz/mv/NabrDDDCG+i3sNGZ\nhZIy07Lv1n07k48GXrp5gdNivru5xBuF57wC/im6OoxrQlPiwcwrJjpVbANSLm8u\n4SqpaC/2kbOl6aO0UVR9Jo1YLNbY8+1fk5YkYqiK0QKBgQDSSKuT26ykXGaXqRuZ\naOUL/ltIt5DNBVMuBAR75ZyxffSrMN+wD3TVGKmPtUHwe4qniroe4zM1B4Ew6TvQ\nMg7rzTI8XjzsRK4labInFn+gzSH1P6RmMMSs1xubxkFxHawq3YCEPkuCZQZVa+xO\n4i3m2wqZGdatQ+OLKb6JlBrteQKBgQC6ukqu4phPUNoyDcIoRJhl5zI1aAv36/U3\nwUnySazu1FoiieJJfNHN+EHF6BdFZRBvJ75nMnrta3McM4vdEys9nXZ0MA161GvQ\nBMHQ/TTM+AYRcMA9n8COTENjw/OHouxfkULWSPTv2gRmAQQkAkDhzqfgckQfk/es\nppTzvCRViQKBgQDBss7ZU/CjNboK2Wri1QynD5VmVjC7qbwFFw5KUicUF8HYLxzd\nQF+OKzmFdqFWs3X0/oSTDxWMM219cFn4XSQBcPJlSSk1Oc5wB/xipQbLSCmPjyAQ\nQbvoufxkcSq2125Pzdkj9332jrhW1yLFRvKhRANvI63rzC09cyZf9F0ZgQKBgHhL\nA0nfGJggUjDkxCwE5NjhNGtLeEpjbDpa/zRjWlER5G9TvL/y9YZnZJgGiNdf4FJ7\nnCIHV0IUcre8TWJCsxyikGkRe92hc0MzjVkBhj51mhMqO+53OClz4AYpen3q67Q1\ndIVvwruyDBtalDxOZ1YRN/1UH6boQCqttk++6PlhAoGAWJYLcFEgcitgUYhA3toV\nOmyhnSgWDpHm6kzMg04GRdgdd4ut7twKVt4rS/7Cf7s923gcK+cq6jeJBoxuG1bB\nbIN745d7h/5EoDVB72cWzlRv+9jvOGwFI4qL/Hejn9Xvj7xUR71cxjQASvGQGP0c\nHGq6HsjJW8mkHTdWtvMRhOM=\n-----END PRIVATE KEY-----\n"
    client_email: data-pipeline@scg-datascience.iam.gserviceaccount.com
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/data-pipeline%40scg-datascience.iam.gserviceaccount.com"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/nexus/certs/scg-datascience-24ba415b4c58.json"
  GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
